### ISSUE TITLE
Numberflow cant inherit parent class

### ISSUE THREAD

**Issue by Lumabots** [barvian/number-flow#79] opened 2024-12-05 10:33 UTC
### NumberFlow version

@number-flow/svelte@0.2.2

### Framework version

svelte@0.2.2

### Describe the bug and the steps to reproduce it

<span
class="inline-flex animate-shine bg-[linear-gradient(110deg,#939393,45%,#1e2631,55%,#939393)] bg-[length:200%_100%] bg-clip-text text-transparent"
>
<NumberFlow class="text-white" value={$botStats.totalUsers} />
</span>

before animation the class with the class will work, however after the class it will be kept as white and not change back to the good color

**Comment by barvian** [comment] 2024-12-05 14:11
Hi 👋, it looks like these styles stop working on relatively or absolutely positioned elements, which NumberFlow unfortunately needs to use: [Chrome bug](https://issues.chromium.org/issues/40858028). I'm closing this for now because I don't see a workaround on my end, unfortunately. I might add it to the limitations section on the docs 😐

**Closed by barvian** 2024-12-05 14:11 UTC

**Comment by barvian** [comment] 2024-12-05 17:07
Hi, wouldn't that mean NumberFlow text disappears during an animation? I might not be following here. Also if you're trying to match the width of NumberFlow with standard text you can use the CSS property `font-kerning: none` 👍

**Comment by Lumabots** [comment] 2024-12-06 06:32
no i was thinking when the animation is completely done it then put the normal font, here is an exemple of what im saying : 

https://github.com/user-attachments/assets/6995aacf-4d4d-42d7-b56a-39c7241d3ee2

However i added the font-kerning: none but it doesnt seems to work, maybe you can drive me a bit on what i should do ? 
here is my code : 
```
<span
class="inline-flex animate-shine bg-[linear-gradient(110deg,#939393,45%,#1e2631,55%,#939393)] bg-[length:200%_100%] bg-clip-text text-transparent"
>
{#if showAnimated}
	<NumberFlow
		class="text-white"
		style="font-kerning: none;"
		value={$botStats.totalGuilds}
		on:animationsfinish={handleAnimationFinish}
	/>
{:else}
	{$botStats.totalGuilds}
{/if}
```

**Comment by Lumabots** [comment] 2024-12-06 19:58
im dumb, it comes from the coma, im sorry about that

**Comment by barvian** [comment] 2024-12-06 20:23
Gotcha, I think this should work instead:

```svelte
<span
class="inline-flex animate-shine bg-[linear-gradient(110deg,#939393,45%,#1e2631,55%,#939393)] bg-[length:200%_100%] bg-clip-text text-transparent"
>
{#if showAnimated}
	<NumberFlow
		class="text-white"
		value={$botStats.totalGuilds}
		on:animationsfinish={handleAnimationFinish}
	/>
{:else}
	<span style="font-kerning: none">{$botStats.totalGuilds}</span>
{/if}
```

**Comment by barvian** [comment] 2024-12-06 20:25
You could also match the formatting of NumberFlow (e.g. adding commas) in this case by doing:

```svelte
<script>
const formatter = new Intl.NumberFormat()
</script>
<!-- ... -->
{:else}
	<span style="font-kerning: none">{formatter.format($botStats.totalGuilds)}</span>
{/if}
```

**Comment by Lumabots** [comment] 2024-12-07 19:50
I also did that however it still moving after

**Comment by Lumabots** [comment] 2024-12-08 19:58
<img width="838" alt="Screenshot 2024-12-08 at 21 58 31" src="https://github.com/user-attachments/assets/9f456436-dbc2-44d1-8e75-1aaadf79f972">

**Comment by barvian** [comment] 2024-12-10 18:08
Hi, would you be able to provide a reproduction for this? I'm not sure what styles you're using so I'm not sure how to provide support. Here's a quick [Svelte sandbox](https://svelte.dev/playground/50830724d003453298791c5ae35fe948?version=5.10.0) I threw together that I think would be a good starting point. Please lmk if you have any questions 👋
